stages:
  lyproxify:
    desc:
      Parse the `raw.csv` data using the `lyscripts` Python package and the `mapping.py`
      module to bring the original data into a format that the online tool LyProX
      understands.
    cmd: >
      lyscripts data lyproxify
      -i raw.csv
      -o data.csv
      -m mapping.py
      -r 0 1 2
      --drop-rows 439
      --add-index
    deps:
      - raw.csv
      - mapping.py
    outs:
      - data.csv:
          cache: false

  data-description:
    desc:
      Generate the description of the `data.csv` columns from the `COLUMN_MAP` inside
      the `mapping.py` file and insert it into the `README.template` to render the
      `README.md` of this dataset.
    deps:
      - README.template
      - render.py
      - mapping.py
    outs:
      - README.partial
    cmd: >
      python render.py

  mapping-docs:
    desc:
      Create a documentation of all the functions in the `mapping.py` module.
    deps:
      - mapping.py
    outs:
      - mapping.py.md
    cmd: >
      ../.venv/bin/lazydocs --output-path=. mapping.py

  concat-readme:
    desc:
      Combine the data description and the mapping documentation in the final `README.md`
    deps:
      - README.partial
      - mapping.py
    outs:
      - README.md
    cmd:
      - ../.venv/bin/lazydocs --output-path=. --no-watermark mapping.py
      - cat README.partial mapping.py.md > README.md

  clean:
    desc:
      Delete intermediate files.
    deps:
      - README.md
    cmd: >
      rm README.partial mapping.py.md
