stages:
  lyproxify:
    desc:
      Parse the `raw.csv` data using the `lyscripts` Python package and the `mapping.py`
      module to bring the original data into a format that the online tool LyProX
      understands.
    cmd: >
      lyscripts data lyproxify
      -i raw.csv
      -o data.csv
      -m mapping.py
      -r 0 1 2
      --drop-rows 439
      --add-index
    deps:
      - raw.csv
      - mapping.py
    outs:
      - data.csv:
          cache: false

  description-and-docs:
    desc:
      Generate the description of the `data.csv` columns from the `COLUMN_MAP` inside
      the `mapping.py` file and insert it into the `README.template` to render the
      `README.md` of this dataset. Then, use lazydocs to generate a documentation of
      the `mapping.py` file and append it to the `README.md`.
    deps:
      - README.template
      - render.py
      - mapping.py
    outs:
      - README.md
    cmd: >
      python render.py
      ../.venv/bin/lazydocs --output-path="README.md" mapping.py
