stages:
  lyproxify:
    foreach:
      - folder: 2023-clb-multisite
        args: "-r 0 1 2 --drop-rows 439 --add-index"
      - folder: 2023-isb-multisite
        args: "-r 0"
    do:
      desc:
        Parse the `raw.csv` data using the `lyscripts` Python package and the
        `mapping.py` module to bring the original data into a format that the online
        interface LyProX understands.
      cmd: >
        lyscripts data lyproxify
        -i ${item.folder}/raw.csv
        -o ${item.folder}/data.csv
        -m ${item.folder}/mapping.py
        ${item.args}
      deps:
        - ${item.folder}/raw.csv
        - ${item.folder}/mapping.py
      outs:
        - ${item.folder}/data.csv:
            cache: false

  description-and-docs:
    foreach:
      - 2023-clb-multisite
      - 2023-isb-multisite
    do:
      desc:
        Generate the description of the `data.csv` columns from the `COLUMN_MAP` inside
        the `mapping.py` file, as well as the documentation of all the functions used
        in the `mapping.py` module. Insert these documentations into the `README.template`
        and create the `README.md` from it.
      deps:
        - render.py
        - ${item}/README.template
        - ${item}/mapping.py
      outs:
        - ${item}/README.md:
            cache: false
      cmd: >
        python /render.py
        -m ${item}/mapping.py
        -t ${item}/README.template
        -o ${item}/README.md
