stages:
  lyproxify:
    desc:
      Parse the `raw.csv` data using the `lyscripts` Python package and the `mapping.py`
      module to bring the original data into a format that the online tool LyProX
      understands.
    cmd: >
      lyscripts data lyproxify
      -i raw.csv
      -o data.csv
      -m mapping.py
      -r 0
    deps:
      - raw.csv
      - mapping.py
    outs:
      - data.csv:
          cache: false
